'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import NavBar from '../../components/NavBar'
import { supabase } from '../../lib/supabaseClient'
import { ResumeSummary } from '../../types'

export default function InsightsPage() {
  const [resume, setResume] = useState<ResumeSummary | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loadResume = async () => {
      const session = await supabase.auth.getSession()
      const jwt = session.data.session?.access_token
      if (!jwt) return

      const response = await fetch('/api/user/resumes', {
        headers: { Authorization: `Bearer ${jwt}` },
      })
      const resumes = await response.json()
      setResume(resumes[0] ?? null)
      setLoading(false)
    }
    loadResume()
  }, [])

  return (
    <main className="min-h-screen bg-slate-50 px-6 py-10 text-slate-950 dark:bg-slate-950 dark:text-slate-100">
      <NavBar />
      <div className="mx-auto max-w-6xl rounded-3xl border border-slate-200 bg-white p-10 shadow-card dark:border-slate-800 dark:bg-slate-900">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <h1 className="text-3xl font-semibold">Resume insights</h1>
            <p className="mt-2 text-slate-600 dark:text-slate-400">Review skill coverage and resume summary generated by Gemini.</p>
          </div>
          <Link href="/upload" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-slate-900 transition hover:border-slate-300 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100">
            Upload another resume
          </Link>
        </div>

        {loading ? (
          <div className="mt-10 rounded-3xl border border-slate-200 bg-slate-50 p-8 dark:border-slate-800 dark:bg-slate-900">
            Loading insights…
          </div>
        ) : resume ? (
          <div className="mt-10 grid gap-8 lg:grid-cols-[1.2fr_0.8fr]">
            <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-card dark:border-slate-800 dark:bg-slate-950">
              <h2 className="text-2xl font-semibold text-slate-950 dark:text-slate-100">AI summary</h2>
              <p className="mt-4 text-slate-700 dark:text-slate-300">{resume.summary || 'A summary will appear once AI processing completes.'}</p>
            </div>
            <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-card dark:border-slate-800 dark:bg-slate-950">
              <h2 className="text-2xl font-semibold text-slate-950 dark:text-slate-100">Top skills</h2>
              <div className="mt-4 flex flex-wrap gap-3">
                {resume.skills.map((skill) => (
                  <span key={skill} className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-100">
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="mt-10 rounded-3xl border border-slate-200 bg-white p-8 shadow-card dark:border-slate-800 dark:bg-slate-900">
            <p className="text-slate-600 dark:text-slate-400">No resume found. Upload your resume to generate insights.</p>
          </div>
        )}
      </div>
    </main>
  )
}
